In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("patient_clinical_data_raw.csv")

In [4]:
df.head(10)

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No
1,P05835,NaN,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No
3,P08789,NaN,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No
5,P02532,31.0,Female,Oncology,104/85,99.0,96.3,196.0,86.0,Hypertension,Routine,5,128417.99,Yes
6,P02996,49.0,MALE,Neurology,118/83,108.0,99.4,192.0,166.0,Heart Disease,Routine,7,106428.84,No
7,P07660,32.0,Female,Pediatrics,122/89,64.0,97.9,186.0,101.0,Cancer,Routine,5,126644.27,No
8,P08225,64.0,Male,Neurology,161/100,61.0,98.5,178.0,85.0,Cancer,Emergency,7,76285.34,No
9,P04449,56.0,Male,General Medicine,102/76,83.0,97.9,263.0,147.0,Migraine,Routine,6,150822.91,No

In [5]:
df.tail(10)

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
10090,P08323,80.0,Female,cardiology,143/68,95.0,98.5,209.0,96.0,Migraine,Referral,6,113362.17,No
10091,P05579,NaN,Male,Orthopedics,130/70,55.0,98.6,210.0,136.0,Migraine,Emergency,6,68281.49,No
10092,P04427,54.0,Female,Neurology,126/93,82.0,98.5,168.0,147.0,Asthma,Referral,4,106702.38,No
10093,P00467,59.0,Female,Cardiology,126/85,81.0,98.4,212.0,150.0,Heart Disease,Routine,6,62179.59,No
10094,P06266,50.0,Female,Pediatrics,123/93,82.0,98.7,185.0,60.0,Infection,Routine,6,108423.54,Yes
10095,P05735,37.0,Female,cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,NaN,Infection,Routine,5,103698.89,No
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No

In [7]:
print("Number of Rows: ", len(df))
print("Number of Columns: ",df.shape[1])

Number of Rows:  10100
Number of Columns:  14

In [8]:
df.describe

<bound method NDFrame.describe of       Patient_ID   Age  Gender        Department Blood_Pressure  Heart_Rate  \
0         P07402  58.0  Female       Orthopedics         119/73        64.0
1         P05835   NaN  Female  General Medicine         107/91        62.0
2         P02123  47.0    Male       Orthopedics         148/98        83.0
3         P08789   NaN    Male          Oncology         115/84        89.0
4         P00305  47.0  Female       Orthopedics         128/62        77.0
...          ...   ...     ...               ...            ...         ...
10095     P05735  37.0  Female        cardiology        155/104        56.0
10096     P05192  47.0  Female       Orthopedics         121/62        78.0
10097     P05391  35.0    Male  General Medicine         108/49        74.0
10098     P00861  51.0  Female        Pediatrics          95/83        86.0
10099     P07271  17.0    Male          Oncology          96/63        81.0

       Temperature  Cholesterol  Glucose      Diagnosis Admission_Type  \
0            100.0        197.0     60.0  Heart Disease       Referral
1             98.8        215.0     92.0       Migraine       Referral
2             96.0        196.0    133.0       Fracture        Routine
3            100.1        224.0    119.0   Hypertension       Referral
4            100.3        184.0    113.0   Hypertension      Emergency
...            ...          ...      ...            ...            ...
10095        101.2        173.0     60.0         Cancer      Emergency
10096         97.8        168.0      NaN      Infection        Routine
10097         99.3        156.0    140.0       Diabetes       Referral
10098         98.6        258.0    110.0  Heart Disease       Referral
10099         99.0        165.0    114.0  Heart Disease       Referral

       Length_of_Stay  Treatment_Cost Readmission
0                   5        91183.33          No
1                   5        71104.32          No
2                   7       135197.73          No
3                   6       146462.06          No
4                   6        57510.66          No
...               ...             ...         ...
10095               7       158883.26          No
10096               5       103698.89          No
10097               7       129075.91          No
10098               4       100906.67          No
10099               5       121905.87          No

[10100 rows x 14 columns]>

In [10]:
df.nunique().to_frame(name='Unique Values')

                Unique Values
Patient_ID              10000
Age                        92
Gender                      5
Department                  9
Blood_Pressure           3645
Heart_Rate                 75
Temperature                76
Cholesterol               206
Glucose                   145
Diagnosis                   8
Admission_Type              3
Length_of_Stay             14
Treatment_Cost           9998
Readmission                 2

In [16]:
# Columns Containing Missing Values
columnsContaingMissingValues = df.columns[df.isna().any()].tolist()

In [15]:
missing_summary = pd.DataFrame({
    'Missing Count': df.isna().sum(),
    'Percentage (%)': df.isna().mean() * 100
})

# Filter out rows with 0 missing values and display
missing_summary[missing_summary['Missing Count'] > 0].sort_values(by='Percentage (%)', ascending=False)

             Missing Count  Percentage (%)
Temperature            304        3.009901
Cholesterol            303        3.000000
Age                    302        2.990099
Heart_Rate             302        2.990099
Glucose                302        2.990099

In [17]:
df[columnsContaingMissingValues] = df[columnsContaingMissingValues].fillna(df[columnsContaingMissingValues].median())

In [18]:
df.columns[df.isna().any()].tolist()

[]

In [19]:
# Remove duplicate rows and modify the DataFrame in place
df.drop_duplicates(inplace=True)

In [20]:
len(df)

10000

In [21]:
# Check the range, min, and max of the Age column
df['Age'].describe()

count    10000.000000
mean        47.390900
std         17.758374
min         -5.000000
25%         36.000000
50%         47.000000
75%         59.000000
max        150.000000
Name: Age, dtype: float64

In [28]:
df = df[(df['Age'] >= 1) & (df['Age'] <= 120)]

In [29]:
len(df)

9985

In [30]:
df['Age'].describe()

count    9985.000000
mean       47.391988
std        17.544563
min         1.000000
25%        36.000000
50%        47.000000
75%        59.000000
max        90.000000
Name: Age, dtype: float64

In [31]:
# Check unique categories and their frequencies for Gender
print("--- Gender Counts ---")
print(df['Gender'].value_counts(dropna=False))

print("\n--- Department Counts ---")
print(df['Department'].value_counts(dropna=False))

--- Gender Counts ---
Gender
Male        4910
Female      4775
MALE         100
male         100
 FEMALE      100
Name: count, dtype: int64

--- Department Counts ---
Department
Oncology            1660
Orthopedics         1643
Neurology           1611
Pediatrics          1611
General Medicine    1604
Cardiology          1556
 CARDIOLOGY          100
cardiology           100
neurology            100
Name: count, dtype: int64

In [32]:
# Clean the Gender column: remove hidden spaces and force Title Case
df['Gender'] = df['Gender'].astype(str).str.strip().str.title()

# Clean the Department column: remove hidden spaces and force Title Case
df['Department'] = df['Department'].astype(str).str.strip().str.title()

In [33]:
print("--- Gender Counts ---")
print(df['Gender'].value_counts(dropna=False))

print("\n--- Department Counts ---")
print(df['Department'].value_counts(dropna=False))

--- Gender Counts ---
Gender
Male      5110
Female    4875
Name: count, dtype: int64

--- Department Counts ---
Department
Cardiology          1756
Neurology           1711
Oncology            1660
Orthopedics         1643
Pediatrics          1611
General Medicine    1604
Name: count, dtype: int64

In [34]:
# Define the bin edges and the matching labels
bins = [-float('inf'), 17, 40, 60, float('inf')]
labels = ['Child', 'Young Adult', 'Middle Age', 'Senior']

# Create the new column using pd.cut
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True)

In [35]:
df

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No,Middle Age
1,P05835,47.0,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No,Middle Age
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No,Middle Age
3,P08789,47.0,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No,Middle Age
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No,Middle Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10095,P05735,37.0,Female,Cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No,Young Adult
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,105.0,Infection,Routine,5,103698.89,No,Middle Age
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No,Young Adult
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No,Middle Age
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No,Child

In [36]:
df['Blood_Pressure']

0         119/73
1         107/91
2         148/98
3         115/84
4         128/62
          ...
10095    155/104
10096     121/62
10097     108/49
10098      95/83
10099      96/63
Name: Blood_Pressure, Length: 9985, dtype: object

In [44]:
df[['Systolic', 'Diastolic']] = df['Blood_Pressure'].str.split('/', expand=True).astype(int)

In [45]:
df.head()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No,Middle Age,119,73
1,P05835,47.0,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No,Middle Age,107,91
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No,Middle Age,148,98
3,P08789,47.0,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No,Middle Age,115,84
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No,Middle Age,128,62

In [46]:
import numpy as np 
df['High_Risk'] = np.where(
    (df['Systolic'] >= 140) | 
    (df['Diastolic'] >= 90) | 
    (df['Cholesterol'] >= 240) | 
    (df['Glucose'] >= 126) | 
    (df['Diagnosis'].isin(['Heart Disease', 'Hypertension'])),
    'Yes', 
    'No'
)

In [48]:
df.tail()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk
10095,P05735,37.0,Female,Cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No,Young Adult,155,104,Yes
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,105.0,Infection,Routine,5,103698.89,No,Middle Age,121,62,No
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No,Young Adult,108,49,Yes
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No,Middle Age,95,83,Yes
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No,Child,96,63,Yes

In [49]:
df['Cost_Per_Day']=df['Treatment_Cost']/df['Length_of_Stay']

In [50]:
df.tail()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
10095,P05735,37.0,Female,Cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No,Young Adult,155,104,Yes,22697.608571
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,105.0,Infection,Routine,5,103698.89,No,Middle Age,121,62,No,20739.778000
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No,Young Adult,108,49,Yes,18439.415714
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No,Middle Age,95,83,Yes,25226.667500
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No,Child,96,63,Yes,24381.174000

In [53]:
print("Average Age: ",df['Age'].mean())

Average Age:  47.39198798197296

In [57]:
print("number of patients in each department", df['Department'].value_counts())

number of patients in each department Department
Cardiology          1756
Neurology           1711
Oncology            1660
Orthopedics         1643
Pediatrics          1611
General Medicine    1604
Name: count, dtype: int64

In [58]:
# Calculate the average treatment cost grouped by department
df.groupby('Department')['Treatment_Cost'].mean()

Department
Cardiology          101941.652659
General Medicine    100766.489707
Neurology           101243.304267
Oncology             99990.091458
Orthopedics         100322.036805
Pediatrics           99006.908237
Name: Treatment_Cost, dtype: float64

In [59]:
df.groupby('Diagnosis')['Length_of_Stay'].mean()

Diagnosis
Asthma           4.991352
Cancer           4.992947
Diabetes         5.081633
Fracture         5.030629
Heart Disease    5.003342
Hypertension     5.099359
Infection        5.022871
Migraine         5.045894
Name: Length_of_Stay, dtype: float64

In [60]:
# Returns the 10 rows with the highest treatment cost
df.nlargest(10, 'Treatment_Cost')

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
1796,P09106,41.0,Male,Neurology,117/73,88.0,98.1,186.0,121.0,Infection,Routine,12,315212.62,Yes,Middle Age,117,73,No,26267.718333
10066,P01900,42.0,Female,Orthopedics,131/84,78.0,97.0,175.0,77.0,Infection,Referral,11,288519.47,No,Middle Age,131,84,No,26229.042727
4832,P06995,36.0,Male,Oncology,150/78,80.0,95.0,200.0,108.0,Asthma,Routine,12,286702.48,Yes,Young Adult,150,78,Yes,23891.873333
7376,P09616,55.0,Male,Neurology,137/76,66.0,96.1,191.0,98.0,Cancer,Emergency,11,285387.70,No,Middle Age,137,76,No,25944.336364
3683,P07933,44.0,Female,Oncology,122/69,87.0,98.4,244.0,108.0,Fracture,Emergency,12,278888.31,No,Middle Age,122,69,Yes,23240.692500
1688,P03835,30.0,Female,Neurology,120/86,66.0,100.2,198.0,81.0,Hypertension,Referral,10,273491.74,No,Young Adult,120,86,Yes,27349.174000
1595,P01350,43.0,Male,Pediatrics,140/89,80.0,98.3,180.0,108.0,Hypertension,Routine,11,273458.79,No,Middle Age,140,89,Yes,24859.890000
4718,P01358,55.0,Male,Orthopedics,85/54,59.0,98.3,208.0,60.0,Infection,Referral,10,273007.12,No,Middle Age,85,54,No,27300.712000
4771,P08810,61.0,Male,Pediatrics,80/70,63.0,97.0,171.0,101.0,Diabetes,Emergency,11,271716.86,No,Senior,80,70,No,24701.532727
925,P07801,32.0,Male,Neurology,138/73,61.0,98.7,209.0,130.0,Heart Disease,Emergency,10,269594.52,No,Young Adult,138,73,Yes,26959.452000

In [61]:
# Returns the department name and its average cost
df.groupby('Department')['Treatment_Cost'].mean().nlargest(1)

Department
Cardiology    101941.652659
Name: Treatment_Cost, dtype: float64

In [63]:
# Calculates the percentage of rows where Readmission equals 'Yes'
readmission_pct = (df['Readmission'] == 'Yes').mean() * 100
print(f"Readmission Rate: {readmission_pct:.2f}%")

Readmission Rate: 18.54%

In [64]:
# Calculate the percentage of readmitted patients for each department
readmission_by_dept = df.groupby('Department').apply(lambda x: (x['Readmission'] == 'Yes').mean() * 100).reset_index(name='Readmission_Rate_(%)')

# Sort from highest readmission rate to lowest
readmission_by_dept.sort_values(by='Readmission_Rate_(%)', ascending=False).round(2)

C:\Users\gurap\AppData\Local\Temp\ipykernel_18044\670055910.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  readmission_by_dept = df.groupby('Department').apply(lambda x: (x['Readmission'] == 'Yes').mean() * 100).reset_index(name='Readmission_Rate_(%)')

         Department  Readmission_Rate_(%)
2         Neurology                 20.57
0        Cardiology                 19.82
5        Pediatrics                 18.56
4       Orthopedics                 18.32
1  General Medicine                 17.83
3          Oncology                 15.96

In [65]:
# Calculate the mean cholesterol and glucose levels grouped by diagnosis
df.groupby('Diagnosis')[['Cholesterol', 'Glucose']].mean()

               Cholesterol     Glucose
Diagnosis
Asthma          197.099843  105.911164
Cancer          195.432602  104.682602
Diabetes        195.022763  107.381476
Fracture        194.125828  105.047185
Heart Disease   196.685881  107.364244
Hypertension    194.140224  107.311699
Infection       193.639590  105.376972
Migraine        195.644122  106.148148

In [66]:
# Define clinical thresholds for high levels
high_glucose_cutoff = 126
high_cholesterol_cutoff = 240
high_heart_rate_cutoff = 100

# Filter the DataFrame for patients meeting ALL three conditions
high_risk_patients = df[
    (df['Glucose'] >= high_glucose_cutoff) & 
    (df['Cholesterol'] >= high_cholesterol_cutoff) & 
    (df['Heart_Rate'] > high_heart_rate_cutoff)
]

# Display key details of these patients
high_risk_patients[['Patient_ID', 'Age', 'Diagnosis', 'Glucose', 'Cholesterol', 'Heart_Rate']]

      Patient_ID   Age      Diagnosis  Glucose  Cholesterol  Heart_Rate
840       P05652  49.0         Cancer    138.0        270.0       103.0
1438      P08941  73.0       Migraine    134.0        257.0       105.0
2125      P02488  47.0         Cancer    133.0        279.0       117.0
3933      P03775  16.0       Diabetes    140.0        255.0       109.0
5165      P06337  60.0  Heart Disease    126.0        256.0       103.0
5498      P02619  56.0       Fracture    131.0        241.0       108.0
6466      P02662  31.0         Asthma    164.0        256.0       101.0
7617      P01423  41.0   Hypertension    172.0        266.0       101.0
10003     P00392  56.0       Fracture    163.0        273.0       101.0