In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("ecommerce_orders_raw.csv")

In [2]:
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0

In [3]:
df.shape

(15100, 11)

In [5]:
df.dtypes

Order_ID             object
Customer_ID          object
City                 object
Product_Category     object
Product              object
Quantity              int64
Unit_Price          float64
Discount              int64
Payment_Method       object
Order_Date           object
Rating              float64
dtype: object

In [6]:
columnsContaingMissingValues = df.columns[df.isna().any()].tolist()

In [7]:
columnsContaingMissingValues

['Rating']

In [9]:
df_duplicate = df[df.duplicated()]

In [32]:
df_duplicate

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
804,O002217,C01672,Chennai,Books,Self Help,5,37140.96,20,Credit Card,2025-03-27 02:24:06.336422428,NaN
921,O001374,C00342,Delhi,Books,Novel,3,49786.14,20,Credit Card,2025-02-22 17:26:28.185879058,4.0
988,O002679,C02462,Pune,Books,Self Help,2,67215.23,10,Cash on Delivery,2025-04-13 20:12:33.650243349,3.0
1046,O002627,C02398,Delhi,Home Appliances,Air Purifier,3,74694.80,15,Credit Card,2025-04-11 20:16:58.627908527,5.0
1198,O014868,C00909,Kolkata,Home Appliances,Air Purifier,1,70777.03,25,Credit Card,2026-07-25 22:20:26.481765448,5.0
...,...,...,...,...,...,...,...,...,...,...,...
14630,O010505,C00257,Coimbatore,Beauty,Skin Serum,4,95997.99,25,UPI,2026-02-08 09:07:54.511634108,3.0
14687,O007418,C02780,Chennai,Beauty,Perfume,2,44950.38,15,Credit Card,2025-10-12 19:57:46.551103408,3.0
14769,O002761,C02646,Bangalore,Sports,Cricket Bat,5,12533.09,5,Credit Card,2025-04-16 23:47:08.108540570,4.0
14883,O013168,C00217,Kolkata,Beauty,Skin Serum,1,24620.22,20,Credit Card,2026-05-21 15:30:58.443896256,4.0
14884,O002849,C01284,Hyderabad,Books,Biography,1,77205.47,15,Cash on Delivery,2025-04-20 08:53:30.454030268,4.0

In [15]:
df['City'].unique()

array(['Delhi', 'Pune', 'Hyderabad', 'Mumbai', 'Kolkata', 'Bangalore',
       ' chennai ', 'Chennai', 'Coimbatore', 'CHENNAI'], dtype=object)

In [16]:
df['Product_Category'].unique()

array(['Home Appliances', 'Books', 'Beauty', 'Sports', 'Clothing',
       'Electronics'], dtype=object)

In [17]:
df['Payment_Method'].unique()

array(['Debit Card', 'Net Banking', 'UPI', 'Credit Card',
       'Cash on Delivery'], dtype=object)

In [18]:
df[columnsContaingMissingValues] = df[columnsContaingMissingValues].fillna(df[columnsContaingMissingValues].median())

In [20]:
df['City']=df['City'].astype(str).str.strip().str.title()

In [21]:
df['City'].unique()

array(['Delhi', 'Pune', 'Hyderabad', 'Mumbai', 'Kolkata', 'Bangalore',
       'Chennai', 'Coimbatore'], dtype=object)

In [25]:
df['Quantity'].describe()

count    15100.000000
mean         3.015629
std          1.430055
min         -2.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Quantity, dtype: float64

In [27]:
df= df[df['Quantity']>0]

In [28]:
df['Quantity'].describe()

count    15080.000000
mean         3.022281
std          1.419281
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Quantity, dtype: float64

In [29]:
df.drop_duplicates(inplace=True)

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [30]:
df.shape

(14980, 11)

In [33]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\2524311366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [36]:
df['Gross_Amount'] = df['Quantity']*df['Unit_Price']

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\139486151.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross_Amount'] = df['Quantity']*df['Unit_Price']

In [37]:
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating,Gross_Amount
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0,20084.16
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0,34791.00
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0,31386.00
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0,363504.30
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0,448564.45

In [38]:
df['Discount_Amount'] = (df['Gross_Amount']*df['Discount'])/100

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\148949742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discount_Amount'] = (df['Gross_Amount']*df['Discount'])/100

In [39]:
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating,Gross_Amount,Discount_Amount
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0,20084.16,2008.4160
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0,34791.00,5218.6500
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0,31386.00,4707.9000
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0,363504.30,72700.8600
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0,448564.45,112141.1125

In [40]:
df['Net_Amount'] = df['Gross_Amount']-df['Discount_Amount']

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\108565910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net_Amount'] = df['Gross_Amount']-df['Discount_Amount']

In [41]:
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating,Gross_Amount,Discount_Amount,Net_Amount
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0,20084.16,2008.4160,18075.7440
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0,34791.00,5218.6500,29572.3500
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0,31386.00,4707.9000,26678.1000
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0,363504.30,72700.8600,290803.4400
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0,448564.45,112141.1125,336423.3375

In [53]:
bins = [-float('inf'), 2, 3, 4, float('inf')]
labels = ['Poor', 'Average', 'Good', 'Excellent']

In [54]:
df['Rating_Category'] = pd.cut(df['Rating'], bins=bins, labels=labels, right=True)

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\2225896779.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating_Category'] = pd.cut(df['Rating'], bins=bins, labels=labels, right=True)

In [55]:
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating,Gross_Amount,Discount_Amount,Net_Amount,Rating_Category
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0,20084.16,2008.4160,18075.7440,Good
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0,34791.00,5218.6500,29572.3500,Poor
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0,31386.00,4707.9000,26678.1000,Good
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0,363504.30,72700.8600,290803.4400,Average
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0,448564.45,112141.1125,336423.3375,Excellent

In [56]:
# 1. Extract the four-digit year (e.g., 2025, 2026)
df['Year'] = df['Order_Date'].dt.year

# 2. Extract the month as a number (1 to 12)
df['Month'] = df['Order_Date'].dt.month

# 3. Extract the day of the month (1 to 31)
df['Day'] = df['Order_Date'].dt.day

# 4. Extract the name of the day of the week (e.g., Thursday, Saturday)
df['Day_of_Week'] = df['Order_Date'].dt.day_name()

# Preview the new columns
print(df[['Order_Date', 'Year', 'Month', 'Day', 'Day_of_Week']].head())

                     Order_Date  Year  Month  Day Day_of_Week
0 2026-07-25 02:03:50.895393024  2026      7   25    Saturday
1 2026-06-27 05:51:34.526301752  2026      6   27    Saturday
2 2026-07-25 15:53:20.613374224  2026      7   25    Saturday
3 2025-02-03 22:44:55.379691979  2025      2    3      Monday
4 2025-01-16 18:48:10.272684845  2025      1   16    Thursday

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\1362732217.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\1362732217.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month
C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\1362732217.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day'] = df['Order_Date'].dt.day
C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\1362732217.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day_of_Week'] = df['Order_Date'].dt.day_name()

In [74]:
total_revenue = df['Net_Amount'].sum()
print(f"Total Revenue: Rs. {total_revenue:,.2f}")

Total Revenue: Rs. 1,981,274,066.40

In [61]:
# Uses nunique() in case an order spans multiple rows/items
total_orders = df['Order_ID'].nunique() 
print(f"Total Orders: {total_orders}")

Total Orders: 14980

In [75]:
# Total revenue divided by the unique number of orders
average_order_value = df['Net_Amount'].mean()
print(f"Average Order Value: Rs. {average_order_value:,.2f}")

Average Order Value: Rs. 132,261.29

In [67]:
revenue_by_category = df.groupby('Product_Category')['Net_Amount'].sum().sort_values(ascending=False)
print(revenue_by_category)

Product_Category
Clothing           3.454173e+08
Books              3.327768e+08
Beauty             3.309898e+08
Sports             3.296359e+08
Electronics        3.235178e+08
Home Appliances    3.189363e+08
Name: Net_Amount, dtype: float64

In [70]:
top_10_products = df.groupby('Product')['Net_Amount'].sum().nlargest(10)
print(top_10_products)

Product
Jeans         9.352895e+07
Jacket        8.884177e+07
Self Help     8.834188e+07
Yoga Mat      8.832334e+07
Shampoo       8.822391e+07
Skin Serum    8.718235e+07
Laptop        8.697328e+07
Mixer         8.529269e+07
Headphones    8.358303e+07
Textbook      8.347781e+07
Name: Net_Amount, dtype: float64

In [72]:
# Groups by city, sums revenue, and grabs the top index name
highest_revenue_city = df.groupby('City')['Net_Amount'].sum().idxmax()
print(f"Highest Revenue City: {highest_revenue_city}")

Highest Revenue City: Chennai

In [76]:
# Grabs the single most common payment method
top_payment_method = df['Payment_Method'].value_counts().idxmax()
print(f"Most Frequent Payment Method: {top_payment_method}")

Most Frequent Payment Method: Debit Card

In [78]:
avg_rating_by_category = df.groupby('Product_Category')['Rating'].mean().sort_values(ascending=False)
print(avg_rating_by_category)

Product_Category
Clothing           3.909875
Beauty             3.897293
Sports             3.882781
Books              3.855216
Home Appliances    3.853001
Electronics        3.832524
Name: Rating, dtype: float64

In [79]:
# Grouping by both Year and Month ensures historical trends stay separated chronologically
monthly_revenue = df.groupby(['Year', 'Month'])['Net_Amount'].sum().reset_index()
print(monthly_revenue)

    Year  Month    Net_Amount
0   2025      1  1.079406e+08
1   2025      2  9.685231e+07
2   2025      3  1.058758e+08
3   2025      4  1.073236e+08
4   2025      5  1.063948e+08
5   2025      6  1.024020e+08
6   2025      7  1.074132e+08
7   2025      8  1.072570e+08
8   2025      9  1.083384e+08
9   2025     10  1.086669e+08
10  2025     11  1.049744e+08
11  2025     12  1.034943e+08
12  2026      1  1.108373e+08
13  2026      2  9.477007e+07
14  2026      3  1.014486e+08
15  2026      4  9.966636e+07
16  2026      5  1.064280e+08
17  2026      6  9.941739e+07
18  2026      7  1.017730e+08

In [94]:
import calendar
highest_month = df.groupby(['Year', 'Month'])['Net_Amount'].sum().idxmax()
year, month = highest_month
print(f"Highest Revenue Month (Year, Month): {calendar.month_name[month]} {year}")

Highest Revenue Month (Year, Month): January 2026

In [83]:
top_10_customers = df.groupby('Customer_ID')['Net_Amount'].sum().nlargest(10)
print(top_10_customers)

Customer_ID
C01527    2.398928e+06
C01856    2.263956e+06
C02170    2.179011e+06
C01626    2.177252e+06
C01882    2.104829e+06
C00990    2.057789e+06
C02988    2.009290e+06
C02588    2.002666e+06
C00139    1.988373e+06
C00944    1.971527e+06
Name: Net_Amount, dtype: float64

In [84]:
# Returns a sorted comparison list of all cities and their financial contributions
city_comparison = df.groupby('City')['Net_Amount'].sum().sort_values(ascending=False).reset_index()
print(city_comparison)

         City    Net_Amount
0     Chennai  2.853485e+08
1      Mumbai  2.478145e+08
2  Coimbatore  2.462794e+08
3       Delhi  2.462605e+08
4        Pune  2.438330e+08
5   Bangalore  2.397697e+08
6     Kolkata  2.392708e+08
7   Hyderabad  2.326976e+08

In [90]:
# First calculate AOV per category: Total Category Revenue / Unique Orders in that category
category_aov = df.groupby('Product_Category').apply(lambda x: x['Net_Amount'].sum() / x['Order_ID'].nunique())
highest_category_aov = category_aov.idxmax()

print(f"Category with Highest AOV: {highest_category_aov} Rs. {category_aov.max():,.2f}")

Category with Highest AOV: Clothing Rs. 135,351.62

C:\Users\gurap\AppData\Local\Temp\ipykernel_12912\4285546140.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  category_aov = df.groupby('Product_Category').apply(lambda x: x['Net_Amount'].sum() / x['Order_ID'].nunique())